# Generated by Django 4.2.3 on 2023-07-11 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle', models.CharField(max_length=100)),
                ('set', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('cooldown_period', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_performed', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('exercises', models.ManyToManyField(through='main_app.ExerciseInWorkout', to='main_app.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseinworkout',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.workout'),
        ),
    ]
