# Generated by Django 4.2.3 on 2023-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle', models.CharField(max_length=100)),
                ('set', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
