# Generated by Django 4.2.3 on 2023-07-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('A', 'Aerobics'), ('B', 'Boxing'), ('C', 'Cardio'), ('P', 'Pilates'), ('S', 'Swimming'), ('W', 'Weightlifting'), ('Y', 'Yoga')], default='S', max_length=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.exercise')),
            ],
        ),
    ]
